# Generated by Django 5.0.7 on 2024-09-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flocation', models.CharField(max_length=255)),
                ('tlocation', models.CharField(max_length=255)),
                ('shortest_distance', models.FloatField()),
                ('path', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.CharField(max_length=100, null=True)),
                ('weight', models.IntegerField(null=True)),
                ('package', models.IntegerField(blank=True, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=65, null=True)),
                ('sender_name', models.CharField(max_length=100, null=True)),
                ('sender_address', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('receiver_name', models.CharField(max_length=100, null=True)),
                ('receiver_address', models.CharField(max_length=100, null=True)),
                ('tracking_number', models.CharField(default='', max_length=12, unique=True)),
                ('is_approve', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('SHIPPED', 'Shipped'), ('IN TRANSIT', 'Transit'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=10)),
                ('current_location', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
