# Generated by Django 5.0.7 on 2024-08-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_parcel_delete_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='id',
        ),
        migrations.AlterField(
            model_name='parcel',
            name='parcelid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
