# Generated by Django 5.0.7 on 2024-08-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_parcel_id_alter_parcel_parcelid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='location',
        ),
        migrations.AddField(
            model_name='parcel',
            name='current_location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='parcel',
            name='destination_location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
