# Generated by Django 5.0.7 on 2024-08-24 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_parcel_location_parcel_current_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('location', models.CharField(default='Unknown', max_length=100)),
                ('parcel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='myapp.parcel')),
            ],
        ),
    ]
