# Generated by Django 5.0.7 on 2024-08-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='expected_delivery',
            field=models.DateField(blank=True, null=True),
        ),
    ]
