# Generated by Django 5.0.7 on 2024-09-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_receiver_sender_shipment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receiver',
        ),
        migrations.DeleteModel(
            name='Sender',
        ),
        migrations.AddField(
            model_name='shipment',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sender_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='goods',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
