# Generated by Django 5.0.7 on 2024-09-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_delete_receiver_delete_sender_shipment_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='dimension',
        ),
        migrations.AddField(
            model_name='shipment',
            name='package',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
