# Generated by Django 5.0.7 on 2024-09-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_shipment_dimension_shipment_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
