# Generated by Django 5.0.7 on 2024-09-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_shipment_shipping_cost_alter_shipment_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
