# Generated by Django 5.0.7 on 2024-09-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_shipment_tracking_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='name',
            new_name='sender_name',
        ),
    ]
