# Generated by Django 5.0.7 on 2024-09-08 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_name_shipment_sender_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking',
            name='parcel',
        ),
        migrations.DeleteModel(
            name='Parcel',
        ),
        migrations.DeleteModel(
            name='Tracking',
        ),
    ]
