# Generated by Django 5.0.7 on 2024-09-09 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_distance_location_delete_route_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Distance',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
