# Generated by Django 5.0.7 on 2024-09-09 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_location_distance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Distance',
        ),
    ]
