# Generated by Django 5.0.7 on 2024-09-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_delete_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('distance', models.FloatField()),
            ],
            options={
                'unique_together': {('from_location', 'to_location')},
            },
        ),
    ]
