# Generated by Django 5.0.7 on 2024-09-09 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_distance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Distance',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
