# Generated by Django 5.0.7 on 2024-09-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_delete_distance_delete_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flocation', models.CharField(max_length=255)),
                ('tlocation', models.CharField(max_length=255)),
                ('shortest_distance', models.FloatField()),
                ('path', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
