# Generated by Django 5.0.7 on 2024-09-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_shipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('SHIPPED', 'Shipped'), ('IN TRANSIT', 'Transit'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=10),
        ),
    ]
