# Generated by Django 5.1 on 2024-09-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_shipment_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
    ]
